# Generated by Django 3.2.4 on 2021-06-11 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя продавца')),
                ('registration_number', models.CharField(max_length=50, verbose_name='Регистрационный номер')),
                ('registration_date', models.DateField(verbose_name='Дата регистрации')),
                ('physical_adress', models.CharField(max_length=200, verbose_name='Физический адресс')),
                ('lint', models.CharField(max_length=50, verbose_name='?')),
                ('organization_person', models.CharField(max_length=50, verbose_name='Имя организации')),
                ('email', models.CharField(max_length=50, verbose_name='Почта продавца')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон продавца')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, verbose_name='Имя продавца')),
                ('password', models.CharField(max_length=50, verbose_name='Имя продавца')),
                ('id_shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.user')),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.shop')),
            ],
        ),
    ]
