# Generated by Django 3.2.4 on 2021-06-12 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210612_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='id',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='login',
        ),
        migrations.RemoveField(
            model_name='client',
            name='id_shop',
        ),
        migrations.RemoveField(
            model_name='client',
            name='id_user',
        ),
    ]
