# Generated by Django 3.2.4 on 2021-06-12 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20210612_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.client'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.client'),
        ),
    ]
