# Generated by Django 3.2.4 on 2021-06-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20210612_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='login',
            new_name='id_shop',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='id_user',
        ),
        migrations.AddField(
            model_name='client',
            name='id_shop',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='id_user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
