# Generated by Django 3.2.4 on 2021-06-12 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20210612_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id_shop',
        ),
        migrations.RemoveField(
            model_name='client',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='id_shop',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_user',
        ),
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.client'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.client'),
        ),
    ]
