# Generated by Django 3.2.4 on 2021-06-12 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_alter_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.client'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.client'),
        ),
    ]
