# Generated by Django 3.2.4 on 2021-06-12 10:16

from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20210612_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.client', verbose_name=registration.models.Client),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.client', verbose_name=registration.models.Client),
            preserve_default=False,
        ),
    ]
