# Generated by Django 3.2.4 on 2021-06-12 10:20

from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20210612_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.client', verbose_name=registration.models.Client),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.client', verbose_name=registration.models.Client),
        ),
    ]
