# Generated by Django 3.2.4 on 2021-06-12 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_auto_20210612_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
    ]
