# Generated by Django 3.2.4 on 2021-06-12 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_auto_20210612_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.AddField(
            model_name='client',
            name='shop',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.shop'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.user'),
        ),
    ]
