# Generated by Django 3.2.4 on 2021-06-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_auto_20210612_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='login',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя продавца'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='email',
            field=models.CharField(max_length=50, unique=True, verbose_name='Почта продавца'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(max_length=50, unique=True, verbose_name='Телефон продавца'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Телефон'),
        ),
    ]
