# Generated by Django 3.2.4 on 2021-06-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_auto_20210615_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Почта продавца'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Телефон продавца'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
    ]
